[tool.poetry]
name = "set-score"
version = "0.0.0"
description = ""
authors = ["Ryuichi OHORI (dalong) <majiang@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
dacite = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
