on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64
      - name: build
        run: |
          mkdir -p build
          python src/__main__.py
      - name: archive
        run: |
          tar --directory build/ -cvf artifact.tar .
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./artifact.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: publish
        id: deployment
        uses: actions/deploy-pages@v1
